# Generated by Django 5.1.1 on 2024-09-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cholesterol',
            field=models.FloatField(default=None, verbose_name='Cholesterol (mg)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='dietary_fibre',
            field=models.FloatField(default=None, verbose_name='dietary_fibre (g)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.FloatField(default=None, verbose_name='protein (g)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='sodium',
            field=models.FloatField(default=None, verbose_name='sodium (mg)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='sugar',
            field=models.FloatField(default=None, verbose_name='sugar (g)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='total_carbo',
            field=models.FloatField(default=None, verbose_name='total_carbo (g)'),
            preserve_default=False,
        ),
    ]
